### ISSUE TITLE
[Bug]: kube-ns-suspender enters in a "deadlock" and stop working

### ISSUE THREAD

**Issue by xakraz** [govirtuo/kube-ns-suspender#110]
### Version

2.2.1

### What happened?

After some time, `kube-ns-suspender` seems to enter into a deadlock 🤷🏻 

Namespaces and supported resources are not processed.
The only thing we can notice is that there has been no more log output since then.

We have setup a basic alert on the logs output rate.
Today we had to restart the deployment several time (~10).

### Relevant log output

```bash
Nothing relevant in the logs
```

### Anything else?

We have ~46 namespaces to manage with ~ 86 deployments and ~ 60 cronjobs each.

💡 Could be interesting to have liveness and readiness probes 😇

**Comment by xakraz** [comment]
@eze-kiel what can I provide to you to help?
Do you have advice for us to try a "fix" on a feature branch of `kube-ns-suspender`?

BTW, we will update our deployment till `2.4.1` today 😅

**Comment by xakraz** [comment]
In one occurrence of the issue, the last log lines were:

```
kube-ns-suspender-main-7c7d6c66c6-9f6r8 kube-ns-suspender {"level":"debug","routine":"suspender","namespace":"feature-fake-key-errors","step":"2/3 - get namespace resources","time":"2023-08-30T17:10:03+02:00","message":"getting namespace resources to manage"}
kube-ns-suspender-main-7c7d6c66c6-9f6r8 kube-ns-suspender {"level":"debug","routine":"suspender","namespace":"feature-fake-key-errors","step":"2/3 - get namespace resources","resource":"deployments","time":"2023-08-30T17:10:03+02:00","message":"get resource from k8s"}
```

❓ Would it be possible the ServiceAccount used by `kube-ns-suspender` deployment reached some kind of quotas regarding the k8s API (GKE specific 🤔 )?

**Comment by eze-kiel** [comment]
@xakraz a new release has been done using the tag `v2.4.1-no-concurrency`. Feel free to try it and keep me posted about the results.

Being stuck may be related to the various concurrency features that are in `kube-ns-suspender`. Removing them may solve the issue.

About the performances, those patterns are here since the first release of kns, so I do not have any benchmark about how much time they save compared to a more traditional mono-routine program. Let's try it this way, and if performance is notably impacted we'll find a workaround.

**Comment by xakraz** [comment]
Hi @eze-kiel  👋🏻 

Thanks for the testing release, I will deploy it tomorrow 🙏🏻 

Here are a few notes about the issue:


## Note01

![image](https://github.com/govirtuo/kube-ns-suspender/assets/1590399/1998263a-e6d2-4e45-9fe0-f9782ff639ea)

We can see that, after the deployment of the `kube-ns-suspender-restarter` workaround I talked you about, there are no more dead-lock/freezes that are noticeable and therefore impact the users of our _FeatureEnvironments_ :check_mark: 


## Note02

![image](https://github.com/govirtuo/kube-ns-suspender/assets/1590399/c032ed49-6b15-4cce-808c-4c2c907c53e1)

While looking for actual “restarts” performed by `kube-ns-suspender-restarter`,

* We can see that there have been a few between Aug 30, 2023 and Aug 31, 2023 (~15).
* BUT no more since … :thinking: 

I have no clue about the reason ....

Anyway, I will deploy the testing release and keep monitoring the restarts performed by `kube-ns-suspender-restarter` to see if there is an improvement.

**Comment by xakraz** [comment]
Hi @eze-kiel!

A quick update since last week 😇 

## Note01

✅  [Release v2.4.1-no-concurrency · govirtuo/kube-ns-suspender](https://github.com/govirtuo/kube-ns-suspender/releases/tag/v2.4.1-no-concurrency) has been deployed on **Sep 6, 2023**


## Note02

![image](https://github.com/govirtuo/kube-ns-suspender/assets/1590399/609966dd-98a0-4a57-9491-ff76b93ce7dd)

✅ By observing the volume of the logs produced by `kube-ns-suspender` we can assume there are **no more issues** since Aug 30, 2023 05:30 PM ... Before the deployment of the `v2.4.1-no-concurrency` 🤔 /🤷🏻 

## Note03

![image](https://github.com/govirtuo/kube-ns-suspender/assets/1590399/3c39746f-2238-43dd-95c7-9fbf5001adba)

✅  **No restart** logged since Aug 31, 2023 02:00 PM ... Same 🤔 /🤷🏻 as for Note02

**Comment by xakraz** [comment]
Totaly agree!

**Comment by apapia** [comment]
I have also run into this.  Although this is marked closed, it seems to be only addressed in a special build for which there is an open PR:
https://github.com/govirtuo/kube-ns-suspender/pull/112

Is there a plan to address this in the main branch?  Thanks!

**Comment by eze-kiel** [comment]
Hi @apapia ! Did you have the issue with the dedicated build?

**Comment by apapia** [comment]
I haven't tried it.  I'm currently running a fork which has an implementation of this feature: https://github.com/govirtuo/kube-ns-suspender/issues/104

Would you like me to contribute that back?

**Comment by eze-kiel** [comment]
Thanks for your PR, I'll have a look!

**Comment by apapia** [comment]
I merged this PR https://github.com/govirtuo/kube-ns-suspender/pull/112 into my private repo.  I have no longer seen a deadlock but now the Web UI does not appear to work.  I see logs when I press the button like this:

{"log":{"level":"info","message":"unsuspended namespace cogito-load using web ui","page":"/unsuspend","routine":"webui","time":"2023-11-15T12:53:33Z"},"stream":"stderr","timestamp":1700052813420}

But the pod keeps seeing the desiredState as suspended:
{"log":{"level":"debug","message":"found annotation 'kube-ns-suspender/desiredState=Suspended'","namespace":"cogito-load","routine":"suspender","step":"1/3 - define namespace state from annotation","time":"2023-11-15T12:59:59Z"},"stream":"stderr","timestamp":1700053199340}

Even though the UI shows it as Running.

If I delete the pod and a new one comes up, the new one sees the correct annotation value:
{"log":{"level":"debug","message":"found annotation 'kube-ns-suspender/desiredState=Running'","namespace":"cogito-load","routine":"suspender","step":"1/3 - define namespace state from annotation","time":"2023-11-15T13:00:13Z"},"stream":"stderr","timestamp":1700053213846}

So it seems that the fix in https://github.com/govirtuo/kube-ns-suspender/pull/112 just causes other problems.  For my purposes, it would be sufficient to just fail a healthcheck when it deadlocks so that the pod gets automatically restarted by Kubernetes.

**Comment by apapia** [comment]
@eze-kiel any thoughts on this?  I'd like to figure out a permanent fix for the deadlock issue that doesn't break the UI.

**Comment by apapia** [comment]
Looks like simply removing the mutex fixes the issue. Please see my PR.

**Comment by apapia** [comment]
I found a second issue after removing the mutex.  Removing the mutex in #115 prevents the watcher and suspender routines from deadlocking.  However, there is a secondary issue in one of our clusters.  We observed that even though the watcher and suspender routines were running, clicking suspend or unsuspend in the UI had no effect on the state of the namespace although the annotation was updated correctly.  The issue turned out to be that the suspender was processing stale namespace state from the watcher.  Restarting the pod would cause it to process the up-to-date state and follow the current annotation.  

The reason the suspender was processing stale state had to do with the WatchListSize and WatcherIdle.  We found that the watcher routine would idle for 15 seconds and then take 2-5 seconds to process the namespace inventory.  However, the suspender would take a little over 2 seconds to process each namespace it received over the channel.  With 12 annotated namespaces, this would take about 24 seconds to process.  Therefore, the Watcher would put more namespaces into the buffered channel than the suspender could process.  Over time, the watcher would completely fill the channel with namespaces to process up to the default of 512 WatchListSize until it would finally start blocking until the suspender had read from the channel.  In this state, the suspender would be processing messages that were many minutes old and so changes to the namespace annotation would not be processed for a very long time.

The simple solution was just to set the WatchListSize to 1.  This results in the watcher simply blocking until the namespace is processed by the suspender routine.  Therefore, the suspender routine is always working with up-to-date namespace state.  I don't see the purpose in queuing up namespace state in the channel that may be out of date by the time it is processed.  Therefore, I would suggest setting the default WatchListSize to 1 or simply using an unbuffered channel.  Thoughts?

**Comment by eze-kiel** [comment]
Hi @apapia, thanks a lot for your work and again, sorry for the late handling of those issues.

I blocked a time slot today to check all your messages and your PR and catch-up everything you've done.

**Comment by eze-kiel** [comment]
Hi again @apapia, your change will be deployed in the new release (`v2.6.0`) in a few minutes.

Thanks
