### ISSUE TITLE
[Bug]: kube-ns-suspender fails on listing cronjobs despite having proper RBAC

### ISSUE THREAD

**Issue by krzwiatrzyk** [govirtuo/kube-ns-suspender#99]
### Version

v2.1.0, v2.2.1,

### What happened?

A bug happened!

As in the title. 

K8s version - v1.25.3

### Relevant log output

```bash
{"level":"debug","routine":"suspender","namespace":"tripper","step":"2/3 - get namespace resources","resource":"cronjobs","time":"2023-01-28T09:21:56+01:00","message":"get resource from k8s"} 

{"level":"fatal","routine":"suspender","namespace":"tripper","error":"the server could not find the requested resource","time":"2023-01-28T09:21:56+01:00","message":"cannot list cronjobs"} 
```

### Anything else?

RBAC applied from customize defined in repository.

**Comment by eze-kiel** [comment]
Hi @krzwiatrzyk, thanks for raising this issue.
Indeed, `kube-ns-suspender` might be a little bit outdated for cronjobs: as you [can see here](https://github.com/govirtuo/kube-ns-suspender/blob/df74db0e526a6ab9ad8d34aab251fcdfd789771b/engine/cronjob.go#L42), we are using `apiVersion: batch/v1beta` to try to find cronjobs. However, since Kubernetes 1.21, Cronjobs are in stable release (`apiVersion: batch/v1`).

So I guess this is why you get this error. Would you mind sharing a cronjob manifest please? Or at least the `apiVersion` field in order for me to confirm this issue?

Thanks

**Comment by krzwiatrzyk** [comment]
Hi, I am using v1.25 version of Kubernetes, so definitely I am using v1/batch version of CronJob so it must be it.

**Comment by eze-kiel** [comment]
I'll try to release a patch soon, I'll keep you posted

**Comment by eze-kiel** [comment]
Hi @krzwiatrzyk, a new version (`v2.3.0`) is currently being built and released. It should solve your issue (the tests are passing).

Please let me know if with this version the issue persists, and feel free to reopen this one!

**Comment by krzwiatrzyk** [comment]
Awesome, I will test it out today, thank you so much!
